<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CourseSearch</title>
    <link rel="stylesheet" type="text/css" href="/styles/styles.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
</head>

<body>

    <?php include 'navbar.php'; ?>
    <header id="home_header">
        <div class="header_container">
            <h1>CourseSearch</h1>
            <p>Excel VBA Application</p>
        </div>
    </header>
    <main>
        <!-- Hero Section -->
        <section class="hero-section">
            <!-- <div class="overlay"></div> -->
            <div class="hero-text">
                <h2>Confused about which courses to take? We've got a solution for you!</h2>
            </div>
        </section>
        <!-- Other Sections -->
        <section class="text-section">
            <p>
                CourseSearch is an interactive excel tool which allows user (YOU!) to enter the courses you have taken so far and gives you a list of courses that you can take in the next semester.
            </p>
        </section>

        <section class="hero-section">
            <!-- <div class="overlay"></div> -->
            <div class="hero-text">
                <h2> What is it?</h2>
            </div>
        </section>
        <section class="text-section">
            <p>
                This tool is an Excel file made for University of Guelph members, mainly for students, but could additionally be utilized by professors and other faculty. Its primary purpose is to tell students what courses they are eligible to take based on past and in-progress courses they have taken. This Excel file can make it easy for students to plan out their future schedules without having to go through all the courses that exist, which includes over 1900 courses.
            </p>
        </section>
        <img class="excel-img" style="width:100%;max-width:500px;padding-bottom:40px;" src="images/excel.png" alt="A screenshot of the form in the Excel, which asks for 'your' average (out of 100), major, and a list of past courses taken. There are two buttons towards the bottom right: 'Show Me Eligible Courses' and 'Restart (clear results page)'." />

        <section class="hero-section">
            <div class="hero-text">
                <h2>Opening the File</h2>
            </div>
        </section>
        <section class="text-section">
            <ol type="1">
                <li>First, download the Excel file you see on this homepage.</li>
                <li>Open the file.</li>
                <li><b>If using Mac:</b> When opening the file, excel will prompt a question about macros and you
                    need to click "enable macros" in order to use the file successfully.</li>
                <li><b>If using Windows:</b> You might need to manually enable macros as Windows security
                    automatically blocks them.</li>
            </ol>
            <p>Click the button below to download:</p>
            <a class="download-button" href="download.php">Download</a>
        </section>

        <section class="hero-section">
            <!-- <div class="overlay"></div> -->
            <div class="hero-text">
                <h2>Using the File</h2>
            </div>
        </section>
        <section class="text-section">
            <ul>
                <li>There are 3 Excel sheets in the file. These can be viewed at the bottom and they are
                    named "allCourses", "courseSearch", and "results".</li>
                <li>The "allCourses" sheet stores every course available. This initial list is from our CSV
                    generated by scraping the undergraduate calendar.</li>
                <li>The "courseSearch" sheet is the primary tool. There are boxes to enter your average,
                    department, and past or in-progress courses. For best results, you should enter all of
                    your past courses to get accurate results. There are two buttons, "Show Me Eligible
                    Courses" and "Restart (clear results page)".</li>
                <li>When you enter your courses and click “Show me Eligible Courses”, the VBA checks
                    your entered courses against the allCourses CSV. If a match is not found, the tool will
                    not generate the possible courses. A message box will instead pop up informing you
                    “Not all courses you entered are valid”. After clicking okay, you will see next to each
                    course in the table will be either “valid course” or “invalid course”. This lets you know
                    which course you entered was invalid. Fix this course before trying again.</li>
                <li>If it is your first search, click "Show Me Eligible Courses" and navigate to the "results"
                    sheet to see the courses you can take. If you have previously done a search, click the
                    restart button to clear the past results before clicking "Show Me Eligible Courses".</li>
                <li>The "results" sheet shows the list of all courses you can take as calculated from the user
                    input. It is in alphabetical order by course code.</li>
            </ul>
        </section>
        <section class="hero-section">
            <!-- <div class="overlay"></div> -->
            <div class="hero-text">
                <h2>Limitations</h2>
            </div>
        </section>
        <!-- Other Sections -->
        <section class="text-section">
            <ul>
                <li>As the Excel file is newly developed, the functionality is not perfect.</li>
                <li>Be sure to read the prerequisites of a course you want to take to double check you are
                    eligible. There are some special cases of courses that the file is not able to account
                    for yet. Some of these special cases include:<ul style="padding-top: 1em;">
                        <li>Registration in a department</li>
                        <li>High school courses</li>
                        <li>Completion of Co-op</li>
                        <li>__ credits in a certain major or department</li>
                    </ul>
                </li>
                <li>Ensure you read the restrictions column of your resulting eligible courses, as they may
                    add additional restrictions that could make you ineligible for the course.</li>
            </ul>
        </section>
    </main>

    <footer>
        <p>&copy; 2023 CourseSearch</p>
    </footer>

</body>

</html>